default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: postgres

development:
  <<: *default
  database: blog_development2

test:
  <<: *default
  database: blog_test2

production:
  <<: *default
  database: <%= ENV['DDATABASE_URL']  %>
