default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: blog_development2

test:
  <<: *default
  database: blog_test2

production:
  <<: *default
  database: <%= ENV['DATABASE_URL']  %>
